version: "3.9"
networks:
  roboshop:
   driver: bridge
services:
  mongodb:
   image: mbhargavi449/mongodb:v1
   container_name: mongodb
  catalogue:
   image: mbhargavi449/catalogue:v1
   container_name: catalogue
   depends_on:
   - mongodb
  web:
   image: mbhargavi449/web:v1
   container_name: web
   depends_on:
   - catalogue
  redis:
   image: redis
  user:
   image: mbhargavi449/user:v1
   container_name: user
   depends_on:
   - mongodb
   - redis       

